config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from django.conf import settings

from core.search import SearchDoc

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.login.urls')),
    
    #APLICACIONES
    path('erp/', include('core.erp.urls')),
    path('user/',include('core.user.urls')),
    path('dashboard/',include('core.dashboard.urls')),
    path('search_doc/',SearchDoc.as_view(),name="search_doc")
    #API
   
]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

core/dashboard/urls.py
from django.urls import path
from .views.views import Dashboard1, PageNotFoundView,ShowAppMovil,Dashboard
from .report.views import ReporteControlAccesos
handler404 = PageNotFoundView.as_view()
app_name = 'dashboard'
urlpatterns = [
    # Otras URLs de tu aplicación
    path('report/', Dashboard.as_view(), name='dash_report'),
    # path('report/', Dashboard1.as_view(), name='dash_report'),
    path('pdf/reporte-1/', ReporteControlAccesos.as_view(), name='reporte_control_accesos'),
    path('data/movil/', ShowAppMovil.as_view(), name='list_data_movil'),
]

core/erp/urls.py
from django.urls import path
from .views.visitas.views import*
from .views.salas.views import*
from .views.parqueo.views import*
from .views.trabajadores.views import*
from .views.ingre_salidas.views import CreateViewIngSal,ListViewIngSal,UpdateViewIngSal,DeleteViewIngSal,AuditoriaIngSalView
from .views.empresas.views import*
from .views.unidad.views import*
from .views.puesto.views import*
from .views.equipos.views import*
from .views.cargos.views import*
from .views.views import PageNotFoundView
from .views.area_trabajo.views import CreateViewAreaTrabajo,ListViewAreaTrabajo,UpdateViewAreaTrabajo,DeleteViewAreaTrabajo
from .views.control_celepsa.views import CreateViewControlCelepsa
handler404 = PageNotFoundView.as_view()
app_name = 'erp'
urlpatterns = [
    #EMPRESAS
    path('empresa/list/',LisViewEmpresa.as_view(),name="empresa_list"),
    path('empresa/add/',CreateViewEmpresa.as_view(),name="empresa_create"),
    path('empresa/update/<int:pk>/',UpdateViewEmpresa.as_view(),name="empresa_update"),
    path('empresa/delete/<int:pk>/',DeleteViewEmpresa.as_view(),name="empresa_delete"),
    #UNIDAD
    path('unidad/list/',ListViewUnidad.as_view(),name='unidad_list'),
    path('unidad/add/',CreateViewUnidad.as_view(),name='unidad_create'),
    path('unidad/edit/<int:pk>/',UpdateViewUnidad.as_view(),name='unidad_update'),
    path('unidad/delete/<int:pk>/',DeleteViewUnidad.as_view(),name='unidad_delete'),
    #PUESTO
    path('puesto/list/',ListViewPuesto.as_view(),name='puesto_list'),
    path('puesto/add/',CreateViewPuesto.as_view(),name='puesto_create'),
    path('puesto/edit/<int:pk>/',UpdateViewPuesto.as_view(),name='puesto_update'),
    path('puesto/delete/<int:pk>/',DeleteViewPuesto.as_view(),name='puesto_delete'),
    #VISITAS
    path('visita/create/',CreateViewVisita.as_view(),name="visita_create"),
    path('visita/list/',ListViewVisita.as_view(),name="visita_list"),
    path('visita/update/<int:pk>/',UpdateViewVisita.as_view(),name="visita_edit"),
    path('visita/delete/<int:pk>/',DeleteViewVisita.as_view(),name="visita_delete"),
    path('visita/audi/<int:pk>/',AuditoriaVisitaView.as_view(),name="visita_audi"),
    #EQUIPOS DE PROTECCION DEL VISITANTE
    path('visita/ep/<int:pk>/',UpdateViewEquipos.as_view(),name="visita_ep_update"),

    #ASISTEN EN LA VISITA
    path('visita/asis/add/',CreateViewAsist.as_view(),name="asis_create"),
    #EPS
    path('epps/list/',ViewEPPS.as_view(),name="epps_list"),
    # path('visita/update/<int:pk>/',UpdateViewVisita.as_view(),name="visita_edit"),
    # path('visita/delete/<int:pk>/',DeleteViewVisita.as_view(),name="visita_delete"),
    #DELIVERY/COURRIER
    path('delivery/create/',CreateViewDelivery.as_view(),name="delivery_create"),
    path('delivery/update/<int:pk>/',UpdateViewDelivery.as_view(),name="delivery_edit"),
    #SALAS
    path('sala/create/',CreateViewSala.as_view(),name="sala_create"),
    path('sala/list/',ListViewSala.as_view(),name="sala_list"),
    path('sala/update/<int:pk>/',UpdateViewSala.as_view(),name="sala_edit"),
    path('sala/delete/<int:pk>/',DeleteViewSala.as_view(),name="sala_delete"),
    path('sala/audi/<int:pk>/',AuditoriaSalaView.as_view(),name="sala_audit"),
    #PARQUEO
    path('parqueo/create/',CreateViewParqueo.as_view(),name="parqueo_create"),
    path('parqueo/list/',ListViewParqueo.as_view(),name="parqueo_list"),
    path('parqueo/update/<int:pk>/',UpdateViewParqueo.as_view(),name="parqueo_edit"),
    path('parqueo/delete/<int:pk>/',DeleteViewParqueo.as_view(),name="parqueo_delete"),
    #CARGO TRABAJADOR
    path('cargo/create/',CreateViewCargo.as_view(),name="cargo_create"),
    path('cargo/list/',ListViewCargo.as_view(),name="cargo_list"),
    path('cargo/update/<int:pk>/',UpdateViewCargo.as_view(),name="cargo_edit"),
    path('cargo/delete/<int:pk>/',DeleteViewCargo.as_view(),name="cargo_delete"),
    #TRABAJADORES
    path('trab/create/',CreateViewTrabajador.as_view(),name="trabajador_create"),
    path('trab/list/',ListViewTrabajador.as_view(),name="trabajador_list"),
    path('trab/update/<int:pk>/',UpdateViewTrabajador.as_view(),name="trabajador_edit"),
    path('trab/delete/<int:pk>/',DeleteViewTrabajador.as_view(),name="trabajador_delete"),
    #INGRESO Y SALIDAS DE TRABAJADORES
    path('ingsal/list/',ListViewIngSal.as_view(),name='ingsal_list'),
    path('ingsal/add/',CreateViewIngSal.as_view(),name='ingsal_create'),
    path('ingsal/edit/<int:pk>/',UpdateViewIngSal.as_view(),name='ingsal_update'),
    path('ingsal/delete/<int:pk>/',DeleteViewIngSal.as_view(),name='ingsal_delete'),
    path('ingsal/audi/<int:pk>/',AuditoriaIngSalView.as_view(),name="ingsal_audi"),

    #UNIDADES DE TRABAJO
    path('area/trabajo/add/',CreateViewAreaTrabajo.as_view(),name='area_trabajo_create'),
    path('area/trabajo/list/',ListViewAreaTrabajo.as_view(),name='area_trabajo_list'),
    path('area/trabajo/update/<int:pk>/',UpdateViewAreaTrabajo.as_view(),name='area_trabajo_update'),
    path('area/trabajo/delete/<int:pk>/',DeleteViewAreaTrabajo.as_view(),name='area_trabajo_delete'),
    #CONTROL CELEPSA
    path("control/celepsa/add/",CreateViewControlCelepsa.as_view(),name="control_add"),
]

core/user/urls.py
from django.urls import path

from core.user.views import ListViewUser,CreateViewUser,DeleteViewUser,UpdateViewUser,UserChangeGroup,UpdatePermissionsView,UserConfigView
app_name = 'user'
urlpatterns = [
    #USUARIO
    path('usuario/list/', ListViewUser.as_view(), name='user_list'),
    path('usuario/create/', CreateViewUser.as_view(), name='user_create'),
    path('usuario/delete/<int:pk>/', DeleteViewUser.as_view(), name='user_delete'),
    path('usuario/update/<int:pk>/', UpdateViewUser.as_view(), name='user_update'),
    path('usuario/change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    # path('usuario/perms/', SelectPermissionsView.as_view(), name='user_perms_create'),
    path('usuario/perms/<int:pk>/', UpdatePermissionsView.as_view(), name='user_perms_update'),
    path("usuario/config/",UserConfigView.as_view(),name="user_config"),
    
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <!-- <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{request.user.get_full_name}}</small></h1>
                        </div>
                       
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'dashboard:dash_report' %}"">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entidad }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script type="">
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
{% load static %}
<script src="{% static 'lib/jquery-confirm/jquery-confirm.min.js' %}"></script>

<nav class="main-header navbar navbar-expand navbar-dark " id="header-title">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'dashboard:dash_report' %}" class="nav-link">Inicio</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li>
            <strong id="fecha-hora"></strong>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">

        {% if request.user.groups.all %}
        <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{
                request.session.group }}</a>
            {% if request.user.groups.all.count > 1 %}
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                style="left: 0px; right: inherit;">
                {% for g in request.user.groups.all %}
                {% if g.id != request.session.group.id %}
                <li><a href="{% url 'user:user_change_group' g.id %}" class="dropdown-item">{{ g.name }} </a></li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
        </li>
        {% endif %}
        <li class="nav-item d-flex dropdown">
            <a class="nav-link" id="dropdownSubMenu2">
                <i class="fas fa-bell" aria-hidden="true"></i>
                <span id="canti" class="badge bg-danger"
                    style="position: absolute;top: 0;right: 0;transform: translate(10%,-10%);"></span>
            </a>
            <form  id="logout-form">
                {% csrf_token %}
                <a class="nav-link" id="salir">
                    <i class="fas fa-power-off"></i> 
                </a>
            </form>
            
            
        </li>
    </ul>
</nav>
<script>
    function mostrarHoraFecha() {
        const ahora = new Date();
        const diaSemana = ahora.toLocaleString('es-ES', { weekday: 'long' });
        const dia = ahora.toLocaleString('es-ES', { day: 'numeric' });
        const mes = ahora.toLocaleString('es-ES', { month: 'long' });
        const ano = ahora.toLocaleString('es-ES', { year: 'numeric' });
        const hora = ahora.toLocaleString('es-ES', { hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: false });

        const fechaHora = `${diaSemana}, ${dia} de ${mes} de ${ano}, ${hora}`;
        document.getElementById('fecha-hora').textContent = fechaHora;
    }

    // Actualizar cada segundo (1000 ms)
    setInterval(mostrarHoraFecha, 1000);

    // Mostrar la hora y fecha por primera vez al cargar la página
    mostrarHoraFecha();
    $(document).ready(function(){
        $('#salir').on("click",function(e){
            event.preventDefault()
            $.confirm({
            theme: 'material',
            title: 'Alerta',
            icon: 'fas fa-info',
            content: "¿Esta seguro que desea salir?",
            columnClass: 'small',
            typeAnimated: true,
            cancelButtonClass: 'btn-primary',
            draggable: true,
            dragWindowBorder: false,
            buttons: {
                info: {
                    text: 'Si',
                    btnClass: 'btn-primary',
                    action: function () {
                        $.ajax({
                            url: "{% url 'logout' %}",
                            type: 'POST',
                            data:{
                                'csrfmiddlewaretoken':'{{ csrf_token }}'
                            },
                            success: function () {
        
                                window.location.href = "{% url 'login' %}"
                            },
                            error: function (xhr, status, error) {
                                alert('Ocurrio un error: ' + status + error)
                            }
                        })
                    }
                },
                danger: {
                    text: 'No',
                    btnClass: 'btn-red',
                    action: function () {

                    }
                }
            },
            })
        })
    })
    

</script>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4 " id="side" style="background-color: #e57f2d;">
    <a class="text-center" href="{% url 'dashboard:dash_report' %}">
        <img src="{% static 'img/logo.png' %}" alt="Control de visitas" class="brand-image"
            style="display: block; margin: auto; width: 90%; height: 100px;">
    </a>
    
    <div class="sidebar">
        <a href="{% url 'dashboard:dash_report' %}" class="" style="margin-left: 40px;font-weight: bold;color: white;">CONTROL DE VISITAS</a>
        <div class="user-panel mt-3 pb-3 mb-3 d-block">
            <div>
                <strong class="text-white">Usuario:</strong>
                <a class="text-white" href="#">{{request.user.username}}</a>
            </div>
            <div>
                <strong class="text-white">Empresa:</strong>
                <a class="text-white" href="#">{{request.user.empresa}}</a>
            </div>
            <div>
                <strong class="text-white">Unidad:</strong>
                <a class="text-white" href="#">{{request.user.unidad}}</a>
            </div>
            <div>
                <strong class="text-white">Puesto:</strong>
                <a class="text-white" href="#">{{request.user.puesto}}</a>
            </div>
        </div>
        <nav class="mt-2">
            
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header text-white">Mantenimientos</li>
                {% if request.user.is_superuser  or request.user.is_staff %}     
                    <li class="nav-item">
                        <a href="{% url 'user:user_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-user text-white"></i>
                            <p class="text-white">
                                Usuarios
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'erp:area_trabajo_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-sitemap text-white"></i>
                            <p class="text-white">
                                Areas de trabajo
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'erp:cargo_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-user-tie text-white"></i>
                            <p class="text-white">
                                Cargos
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'erp:empresa_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-industry text-white"></i>
                            <p class="text-white">
                                Empresas
                            </p>
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'erp:unidad_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-location-arrow text-white"></i>
                        <p class="text-white">
                            Unidades
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:puesto_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-id-card text-white"></i>
                        <p class="text-white">
                            Puestos
                        </p>
                    </a>
                </li>
                
                <li class="nav-item">
                    <a href="{% url 'erp:sala_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-chair text-white"></i>
                        <p class="text-white">
                            Salas
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:parqueo_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-parking text-white"></i>
                        <p class="text-white">
                            Parqueos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:trabajador_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-hard-hat text-white"></i>
                        <p class="text-white">
                            Trabajadores
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                  
                    <a href="{% url 'erp:visita_list' %}" class="nav-link" id="visitas-toggle" style="text-align: left;">
                        <i class="nav-icon fas fa-user-friends text-white"></i>
                        <p class="text-white">
                           Visitas
                        </p>
                    </a>
                 
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:ingsal_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-clock text-white"></i>
                        <p class="text-white">
                            Control de Personal
                        </p>
                    </a>
                </li>
                <!-- <li class="nav-item">
                    <a href="{% url 'erp:control_add' %}" class="nav-link">
                        <i class="nav-icon fas fa-clock text-white"></i>
                        <p class="text-white">
                            Control de Celepsa
                        </p>
                    </a>
                </li> -->
                <li class="nav-item">
                    <a href="{% url 'dashboard:dash_report' %}" class="nav-link">
                        <i class="nav-icon fas fa-chart-bar text-white"></i>
                        <p class="text-white">
                            Reportes
                        </p>
                    </a>
                </li>
                {% if request.user.is_superuser %}     
                    <li class="nav-item">
                        <a href="{% url 'user:user_config' %}" class="nav-link">
                            <i class="nav-icon fas fa-cog text-white"></i>
                            <p class="text-white">
                                Configuracion
                            </p>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</aside>