config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from django.conf import settings

from core.search import SearchDoc

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.login.urls')),
    
    #APLICACIONES
    path('erp/', include('core.erp.urls')),
    path('user/',include('core.user.urls')),
    path('dashboard/',include('core.dashboard.urls')),
    path('search_doc/',SearchDoc.as_view(),name="search_doc")
    #API
   
]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

core/user/urls.py
from django.urls import path

from core.user.views import ListViewUser,CreateViewUser,DeleteViewUser,UpdateViewUser,UserChangeGroup,UpdatePermissionsView,UserConfigView
app_name = 'user'
urlpatterns = [
    #USUARIO
    path('usuario/list/', ListViewUser.as_view(), name='user_list'),
    path('usuario/create/', CreateViewUser.as_view(), name='user_create'),
    path('usuario/delete/<int:pk>/', DeleteViewUser.as_view(), name='user_delete'),
    path('usuario/update/<int:pk>/', UpdateViewUser.as_view(), name='user_update'),
    path('usuario/change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    # path('usuario/perms/', SelectPermissionsView.as_view(), name='user_perms_create'),
    path('usuario/perms/<int:pk>/', UpdatePermissionsView.as_view(), name='user_perms_update'),
    path("usuario/config/",UserConfigView.as_view(),name="user_config"),
    
]

core/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager
from django.forms import model_to_dict
from crum import get_current_request

from config.settings import MEDIA_URL, STATIC_URL
class Empresa(models.Model):
    ruc = models.CharField(max_length=11,verbose_name="RUC",unique=True)
    razon_social = models.CharField(max_length=150,verbose_name="Razon social")
    direccion = models.CharField(max_length=150,verbose_name="Direccion",null=True,blank=True)
    abreviacion = models.CharField(max_length=10,verbose_name="Abreviacion",null=True,blank=True)

    class Meta:
        verbose_name = 'empresa'
        verbose_name_plural = "empresas"
        db_table = 'empresas'
    def toJSON(self):
        item = model_to_dict(self)
        return item
    def __str__(self) -> str:
        return str(self.razon_social)
class Unidad(models.Model):
    empresa = models.ForeignKey(Empresa,on_delete=models.DO_NOTHING,null=True,blank=True,verbose_name="Empresa")
    unidad = models.CharField(max_length=150,verbose_name="Unidad")


    class Meta:
        verbose_name = "unidad"
        verbose_name_plural = "unidades"
        db_table = 'unidades'
    def toJSON(self):
        item = model_to_dict(self)

        return item 
    def __str__(self) -> str:
        return str(self.unidad)
class Puesto(models.Model):
    unidad = models.ForeignKey(Unidad,on_delete=models.DO_NOTHING,verbose_name="Unidad")
    puesto = models.CharField(max_length=15,verbose_name="Puesto")
    direccion = models.CharField(max_length=150,verbose_name="Direccion")

    class Meta:
        verbose_name = "puesto"
        verbose_name_plural = "puestos"
        db_table = 'puestos'
    def toJSON(self):
        item = model_to_dict(self)
        return item
    def __str__(self) -> str:
        return str(self.puesto)
class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    dni = models.CharField(max_length=10,verbose_name="Documento",null=True,blank=True)
    tipo = models.CharField(max_length=255,null=True,blank=True,verbose_name="Tipo de Usuario")
    image = models.ImageField(upload_to='users/',null=True,blank=True,verbose_name="Imagen")
    last_name = models.CharField(max_length=150, blank=False,verbose_name='Nombre')
    first_name = models.CharField(max_length=30, blank=False,verbose_name="Apellidos")
    empresa = models.ForeignKey(Empresa,on_delete=models.DO_NOTHING,verbose_name="Empresa",null=True,blank=True)
    unidad = models.ForeignKey(Unidad,on_delete=models.DO_NOTHING,verbose_name='Unidad',null=True,blank=True)
    puesto = models.ForeignKey(Puesto,on_delete=models.DO_NOTHING,verbose_name='Puesto',null=True,blank=True)
    tipo_user = models.CharField(max_length=5,verbose_name="Tipo de usuario",choices=[("1","Administrador"),("2","Supervisor"),("3","Usuario")],default="3")
    objects = UserManager()
    def toJSON(self):
        item = model_to_dict(self, exclude=['password', 'user_permissions', 'last_login'])
        if self.last_login:
            item['last_login'] = self.last_login.strftime('%Y-%m-%d')
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['image'] = self.get_image()
        item['full_name'] = self.get_full_name()
        item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]   
        return item
    def get_image(self):
        if self.image:
            return '{}{}'.format(MEDIA_URL, self.image)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')
    def get_group_session(self):
        try:
            request = get_current_request()
            groups = self.groups.all()
            if groups.exists():
                if 'group' not in request.session:
                    request.session['group'] = groups[0]
        except:
            pass
    def __str__(self):
        return f"{self.username}"

    
class UserEmpresas(models.Model):
    usuario = models.ForeignKey(User,on_delete=models.DO_NOTHING,verbose_name="Usuario")
    empresa = models.ForeignKey(Empresa,on_delete=models.DO_NOTHING,verbose_name="Empresas")
    class Meta:
        verbose_name = "Empresa asignada"
        verbose_name_plural = "Empresas asignadas"
        db_table = "user_empresas"
        constraints = [
            models.UniqueConstraint(fields=['usuario', 'empresa'], name='unique_usuario_empresa')
        ]
    def toJSON(self):
        item = model_to_dict(self)
        return item
    def __str__(self) -> str:
        return f"{self.usuario.username}"
class UserSupervisor(models.Model):
    supervisor = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='supervised_users', verbose_name="Supervisor")
    supervised_user = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='supervised_by', verbose_name="Supervisado")

    class Meta:
        verbose_name = "Usuario a cargo"
        verbose_name = "Usuarios a cargo"
        db_table = "users_supervisor"
        constraints = [
            models.UniqueConstraint(fields=["supervisor","supervised_user"],name="unique_supervisor_supervised_user")
        ]
    def toJSON(self):
        item = model_to_dict(self)
        item["supervisor"] = self.supervisor.username
        item["supervised_user"] = self.supervised_user.username
        return item
    def __str__(self) -> str:
        return f"{self.supervisor.username}->{self.supervised_user.username}"

core/user/views.py
from typing import Any
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,View,TemplateView
from core.mixins import PermisosMixins
from core.validation import Validation
from core.user.forms import FormUser,FormUserSupervisor,FormUserEmpresa
from core.user.models import User,Puesto,Unidad,UserSupervisor,Empresa,UserEmpresas
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import PermissionSelectionForm

class ListViewUser(LoginRequiredMixin,PermisosMixins,ListView):
    permission_required = ('user.view_user',)
    login_url = reverse_lazy('login')
    model = User
    template_name = 'user/list.html'
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
           
            if action == 'searchdata':
                data = []
                for i in User.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Usuarios'
        context['create_url'] = reverse_lazy('user:user_create')
        context['list_url'] = reverse_lazy('user:user_list')
        context['entidad'] = 'Usuarios'
        context['is_superuser'] = self.request.user.is_superuser
        return context
class CreateViewUser(LoginRequiredMixin,PermisosMixins,CreateView):
    permission_required = ('user.view_user','user.create_user')
    login_url = reverse_lazy('login')
    model = User
    form_class = FormUser
    template_name = 'user/create.html'
    success_url = reverse_lazy('user:user_list')
    url_redirect = success_url
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}        
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            elif action =='searchdni':
                data = Validation(request.POST['dni'],'dni').valid()
            elif action == 'search_unidad':
                data = []
                for value in Unidad.objects.filter(empresa_id=request.POST['id']):
                    data.append(value.toJSON())
            elif action == 'search_puesto':
                data = []
                for value in Puesto.objects.filter(unidad_id=request.POST['id']):
                    data.append(value.toJSON())
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data,safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de un Usuario'
        context['entidad'] = 'Usuarios'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context
class UpdateViewUser(LoginRequiredMixin,PermisosMixins,UpdateView):
    permission_required = ('user.view_user','user.update_user')
    login_url = reverse_lazy('login')
    model = User
    form_class = FormUser
    template_name = 'user/create.html'
    success_url = reverse_lazy('user:user_list')
    url_redirect = success_url
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)
  
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            elif action =='searchdni':
                data = Validation(request.POST['dni'],'dni').valid()
            elif action == 'search_unidad':
                data = []
                for value in Unidad.objects.filter(empresa_id=request.POST['id']):
                    data.append(value.toJSON())
            elif action == 'search_puesto':
                data = []
                for value in Puesto.objects.filter(unidad_id=request.POST['id']):
                    data.append(value.toJSON())
            elif action == 'searchdni':
                data = Validation(request.POST['dni'],'dni').valid()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data,safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de un Usuario'
        context['entidad'] = 'Usuarios'
        context['list_url'] = self.success_url
        context['action'] = 'edit'
        return context
class DeleteViewUser(LoginRequiredMixin,DeleteView):
    permission_required = ('user.view_user','user.delete_user')
    login_url = reverse_lazy('login')
    model = User
    template_name = 'user/delete.html'
    success_url = reverse_lazy('user:user_list')
    url_redirect = success_url
    
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = 'El usuario tiene registros relacionados, primero elimine los registros que hagan referencia al usuario'
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de un Usuario'
        context['entidad'] = 'Usuarios'
        context['list_url'] = self.success_url
        return context
class UserChangeGroup(LoginRequiredMixin,View):
    login_url = reverse_lazy('login')
    def get(self, request, *args, **kwargs):
        try:
            request.session['group'] = Group.objects.get(pk=self.kwargs['pk'])
        except:
            pass
        return HttpResponseRedirect(reverse_lazy('user:user_list'))


class SelectPermissionsView(CreateView):
    form_class = PermissionSelectionForm
    template_name = 'user/perms.html'  
    success_url = reverse_lazy('user:user_list')  

    def form_valid(self, form):
        data = {}
        try:
            user = form.cleaned_data['user']
            selected_permissions = form.cleaned_data['permissions']
            user.user_permissions.set(selected_permissions)
        except Exception as e:
            data['error'] = f"Ocurrio un error {str(e)}"
        return JsonResponse(data)
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['title'] = "Asignacion de Permisos"
        context['list_url'] = self.success_url
        context['entidad'] = "Permisos"
        return context

class UpdatePermissionsView(UpdateView):
    model = User
    form_class = PermissionSelectionForm
    template_name = 'user/perms.html'
    success_url = reverse_lazy('user:user_list')

    def get(self, request, *args, **kwargs):
        user_id = kwargs.get('pk')
        user = User.objects.get(pk=user_id)
        self.object = user
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Editar Permisos"
        context['entidad'] = "Permisos"
        context['list_url'] = self.success_url
        context['username'] = User.objects.get(id=self.object.id)
        context['action'] = 'edit'
        return context
    def post(self, request, *args, **kwargs):
        data = {}
        if int(request.POST['user'])!=int(kwargs['pk']):
            return JsonResponse({'error':'No se puede cambiar de usuario'})
        
        try:
            action = request.POST['action']
            if action =='edit':
                user = User.objects.get(id=request.POST['user'])
                try:
                    selected_permissions = request.POST.getlist('permissions')
                    user.user_permissions.set(selected_permissions)
                except :
                    user.user_permissions.clear()
      
            else:
                data['error']  = "No ingreso ninguna opcion"
        except:
            data['error'] = f'Error al registrar'
        return JsonResponse(data)
class UserConfigView(TemplateView):
    template_name = 'config/create.html'
    success_url = reverse_lazy('user:user_config')
    url_redirect = success_url
    def post(self,request,*args,**kwargs):
        data = {}
        try:
            action = request.POST["action"]
            if action == "add-1":
                instance = FormUserSupervisor(request.POST)
                instance.save()
            elif action=="add-2":
                instance = FormUserEmpresa(request.POST)
                instance.save()
            else:
                data["error"] = "No se ingreso una opcion"
        except Exception as e:
            data["error"] = f"Ocurrio un error :{str(e)}"
        return JsonResponse(data,safe=False)
    def get_context_data(self,**kwargs):

core/user/templates/config/create.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.7/css/dataTables.bootstrap5.css"/>
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.bootstrap5.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.bootstrap5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.colVis.min.js"></script>
{% endblock head %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        <form id="form-user-supervisor">
            <div class="container">
                <div class="row">
                    <!-- Campo de supervisor -->
                     {% csrf_token %}
                     <input type="hidden" name="action" id="action" value="add-1">
                    <div class="form-group col-12 col-md-4 mb-2">
                        <label for="id_supervisor">{{ form_user_supervisor.supervisor.label }}</label>
                        {{ form_user_supervisor.supervisor }}
                    </div>
        
                    <!-- Campo de usuario supervisado -->
                    <div class="form-group col-12 col-md-4 mb-2">
                        <label for="id_supervised_user">{{ form_user_supervisor.supervised_user.label }}</label>
                        {{ form_user_supervisor.supervised_user }}
                    </div>
        
                    <!-- Botón de guardar -->
                    <div class="form-group col-12 col-md-4 mt-3">
                        <button type="button" id="btn-user-supervisor" class="btn btn-primary btn-sm mt-3">
                            GUARDAR
                        </button>
            
                    </div>
                </div>
            </div>
        </form>
        <div
            class="table-responsive"
        >
            <table
                class="table"
                id="user-supervisor"
               
            >
                <thead>
                    <tr  id="header-title">
                        <th scope="col">ID</th>
                        <th scope="col">Supervisor</th>
                        <th scope="col">Supervisado</th>
                    </tr>
                </thead>
                <tbody>
                    {% for value in data_supervised %}
                        <tr>
                            <td>{{value.id}}</td>
                            <td>{{value.supervisor}}</td>
                            <td>{{value.supervised_user}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>
    <div class="col-md-6">
        <form id="form-user-empresa">
            <div class="container">
                <div class="row">
                    <!-- Campo de supervisor -->
                     {% csrf_token %}
                     <input type="hidden" name="action" id="action" value="add-2">
                    <div class="form-group col-12 col-md-4 mb-2">
                        <label for="id_usuario">{{ form_user_empresa.usuario.label }}</label>
                        {{ form_user_empresa.usuario }}
                    </div>
        
                    <!-- Campo de usuario supervisado -->
                    <div class="form-group col-12 col-md-4 mb-2">
                        <label for="id_empresa">{{ form_user_empresa.empresa.label }}</label>
                        {{ form_user_empresa.empresa }}
                    </div>
        
                    <!-- Botón de guardar -->
                    <div class="form-group col-12 col-md-4 mt-3">
                        <button type="button" id="btn-user-empresa" class="btn btn-primary btn-sm mt-3">
                            GUARDAR
                        </button>
            
                    </div>
                </div>
            </div>
        </form>
        <div
            class="table-responsive"
        >
            <table
                class="table"
                id="user-empresa"
            >
                <thead>
                    <tr  id="header-title">
                        <th scope="col">ID</th>
                        <th scope="col">Usuario</th>
                        <th scope="col">Empresa asignada</th>
                    </tr>
                </thead>
                <tbody>
                    {% for value in data_user_empresa %}
                        <tr>
                            <td>{{value.id}}</td>
                            <td>{{value.usuario}}</td>
                            <td>{{value.empresa}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
$("#btn-user-supervisor").on("click", function(e) {
    e.preventDefault()
    var parameters = new FormData(document.getElementById("form-user-supervisor"));
    submit_with_ajax(window.location.pathname, "Notificación", "¿Está seguro de realizar la acción?", parameters, function() {
        location.href = '{{ list_url }}';
    });
});

    $("#btn-user-empresa").on("click",function(e){
        e.preventDefault()
        var parameters = new FormData(document.getElementById("form-user-empresa"))
        submit_with_ajax(window.location.pathname,"Notificacion","¿Esta seguro de realizar la accion?",parameters,function(){
            location.href = '{{ list_url }}';

        })
        
    })
    new DataTable("#user-empresa",{
        autoWidth:false,
        language:{
                url:"{% static '/lib/datatables/spain.json' %}"
            },
        "order": [[0, 'desc']],
        lengthMenu: [
                [ 10, 25, 50, -1 ],
                [ '10 filas', '25 filas', '50 filas', 'Todo' ]
            ],

    })
    new DataTable("#user-supervisor",{
        autoWidth:false,
        language:{
                url:"{% static '/lib/datatables/spain.json' %}"
            },
        "order": [[0, 'desc']],
        lengthMenu: [
                [ 10, 25, 50, -1 ],
                [ '10 filas', '25 filas', '50 filas', 'Todo' ]
            ],

    }
    )
</script>
{% endblock content %}