config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from django.conf import settings

from core.search import SearchDoc

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.login.urls')),
    
    #APLICACIONES
    path('erp/', include('core.erp.urls')),
    path('user/',include('core.user.urls')),
    path('dashboard/',include('core.dashboard.urls')),
    path('search_doc/',SearchDoc.as_view(),name="search_doc")
    #API
   
]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

core/erp/urls.py
from django.urls import path
from .views.visitas.views import*
from .views.salas.views import*
from .views.parqueo.views import*
from .views.trabajadores.views import*
from .views.ingre_salidas.views import CreateViewIngSal,ListViewIngSal,UpdateViewIngSal,DeleteViewIngSal,AuditoriaIngSalView
from .views.empresas.views import*
from .views.unidad.views import*
from .views.puesto.views import*
from .views.equipos.views import*
from .views.cargos.views import*
from .views.views import PageNotFoundView
from .views.area_trabajo.views import CreateViewAreaTrabajo,ListViewAreaTrabajo,UpdateViewAreaTrabajo,DeleteViewAreaTrabajo
from .views.control_celepsa.views import CreateViewControlCelepsa
handler404 = PageNotFoundView.as_view()
app_name = 'erp'
urlpatterns = [
    #EMPRESAS
    path('empresa/list/',LisViewEmpresa.as_view(),name="empresa_list"),
    path('empresa/add/',CreateViewEmpresa.as_view(),name="empresa_create"),
    path('empresa/update/<int:pk>/',UpdateViewEmpresa.as_view(),name="empresa_update"),
    path('empresa/delete/<int:pk>/',DeleteViewEmpresa.as_view(),name="empresa_delete"),
    #UNIDAD
    path('unidad/list/',ListViewUnidad.as_view(),name='unidad_list'),
    path('unidad/add/',CreateViewUnidad.as_view(),name='unidad_create'),
    path('unidad/edit/<int:pk>/',UpdateViewUnidad.as_view(),name='unidad_update'),
    path('unidad/delete/<int:pk>/',DeleteViewUnidad.as_view(),name='unidad_delete'),
    #PUESTO
    path('puesto/list/',ListViewPuesto.as_view(),name='puesto_list'),
    path('puesto/add/',CreateViewPuesto.as_view(),name='puesto_create'),
    path('puesto/edit/<int:pk>/',UpdateViewPuesto.as_view(),name='puesto_update'),
    path('puesto/delete/<int:pk>/',DeleteViewPuesto.as_view(),name='puesto_delete'),
    #VISITAS
    path('visita/create/',CreateViewVisita.as_view(),name="visita_create"),
    path('visita/list/',ListViewVisita.as_view(),name="visita_list"),
    path('visita/update/<int:pk>/',UpdateViewVisita.as_view(),name="visita_edit"),
    path('visita/delete/<int:pk>/',DeleteViewVisita.as_view(),name="visita_delete"),
    path('visita/audi/<int:pk>/',AuditoriaVisitaView.as_view(),name="visita_audi"),
    #EQUIPOS DE PROTECCION DEL VISITANTE
    path('visita/ep/<int:pk>/',UpdateViewEquipos.as_view(),name="visita_ep_update"),

    #ASISTEN EN LA VISITA
    path('visita/asis/add/',CreateViewAsist.as_view(),name="asis_create"),
    #EPS
    path('epps/list/',ViewEPPS.as_view(),name="epps_list"),
    # path('visita/update/<int:pk>/',UpdateViewVisita.as_view(),name="visita_edit"),
    # path('visita/delete/<int:pk>/',DeleteViewVisita.as_view(),name="visita_delete"),
    #DELIVERY/COURRIER
    path('delivery/create/',CreateViewDelivery.as_view(),name="delivery_create"),
    path('delivery/update/<int:pk>/',UpdateViewDelivery.as_view(),name="delivery_edit"),
    #SALAS
    path('sala/create/',CreateViewSala.as_view(),name="sala_create"),
    path('sala/list/',ListViewSala.as_view(),name="sala_list"),
    path('sala/update/<int:pk>/',UpdateViewSala.as_view(),name="sala_edit"),
    path('sala/delete/<int:pk>/',DeleteViewSala.as_view(),name="sala_delete"),
    path('sala/audi/<int:pk>/',AuditoriaSalaView.as_view(),name="sala_audit"),
    #PARQUEO
    path('parqueo/create/',CreateViewParqueo.as_view(),name="parqueo_create"),
    path('parqueo/list/',ListViewParqueo.as_view(),name="parqueo_list"),
    path('parqueo/update/<int:pk>/',UpdateViewParqueo.as_view(),name="parqueo_edit"),
    path('parqueo/delete/<int:pk>/',DeleteViewParqueo.as_view(),name="parqueo_delete"),
    #CARGO TRABAJADOR
    path('cargo/create/',CreateViewCargo.as_view(),name="cargo_create"),
    path('cargo/list/',ListViewCargo.as_view(),name="cargo_list"),
    path('cargo/update/<int:pk>/',UpdateViewCargo.as_view(),name="cargo_edit"),
    path('cargo/delete/<int:pk>/',DeleteViewCargo.as_view(),name="cargo_delete"),
    #TRABAJADORES
    path('trab/create/',CreateViewTrabajador.as_view(),name="trabajador_create"),
    path('trab/list/',ListViewTrabajador.as_view(),name="trabajador_list"),
    path('trab/update/<int:pk>/',UpdateViewTrabajador.as_view(),name="trabajador_edit"),
    path('trab/delete/<int:pk>/',DeleteViewTrabajador.as_view(),name="trabajador_delete"),
    #INGRESO Y SALIDAS DE TRABAJADORES
    path('ingsal/list/',ListViewIngSal.as_view(),name='ingsal_list'),
    path('ingsal/add/',CreateViewIngSal.as_view(),name='ingsal_create'),
    path('ingsal/edit/<int:pk>/',UpdateViewIngSal.as_view(),name='ingsal_update'),
    path('ingsal/delete/<int:pk>/',DeleteViewIngSal.as_view(),name='ingsal_delete'),
    path('ingsal/audi/<int:pk>/',AuditoriaIngSalView.as_view(),name="ingsal_audi"),

    #UNIDADES DE TRABAJO
    path('area/trabajo/add/',CreateViewAreaTrabajo.as_view(),name='area_trabajo_create'),
    path('area/trabajo/list/',ListViewAreaTrabajo.as_view(),name='area_trabajo_list'),
    path('area/trabajo/update/<int:pk>/',UpdateViewAreaTrabajo.as_view(),name='area_trabajo_update'),
    path('area/trabajo/delete/<int:pk>/',DeleteViewAreaTrabajo.as_view(),name='area_trabajo_delete'),
    #CONTROL CELEPSA
    path("control/celepsa/add/",CreateViewControlCelepsa.as_view(),name="control_add"),
]

core/erp/models.py
from django.db import models
from django.forms import model_to_dict
from config.settings import MEDIA_URL, STATIC_URL
from core.user.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date
from core.user.models import Empresa,Unidad,Puesto
from simple_history.models import HistoricalRecords
# Create your models here.
class AreaTrabajo(models.Model):
    area = models.CharField(max_length=100,verbose_name='Area de trabajo',unique=True)
    class Meta:
        verbose_name = 'Area de trabajo'
        verbose_name_plural = 'Areas de trabajo'
        db_table = 'areas_trabajo'
    def toJSON(self):
        return model_to_dict(self)
    def __str__(self) -> str:
        return self.area
class CargoTrabajador(models.Model):
    cargo = models.CharField(max_length=150,verbose_name="Cargo",unique=True)
    area = models.ForeignKey(AreaTrabajo,on_delete=models.DO_NOTHING,verbose_name='Area de trabajo')
    class Meta:
        verbose_name = "Cargo de Trabajador"
        verbose_name_plural = "Cargos de trabajadores"
        db_table = "cargo_trabajador"
        constraints = [
            models.UniqueConstraint(fields=["cargo","area"],name="unique_cargo_area")
        ]
    def toJSON(self):
        item =  model_to_dict(self)
        item["area"] = self.area.area
        return item
    def __str__(self):
        return self.cargo
class Trabajadores(models.Model):
    tipo = models.CharField(max_length=3,choices=[('1',"DNI"),('2',"C.E"),('3',"PASAPORTE")],blank=True,null=True)
    documento = models.CharField(max_length=10,verbose_name="Documento",unique=True)
    nombre = models.CharField(max_length=25,verbose_name="Nombres")
    apellidos = models.CharField(max_length=50,verbose_name="Apellidos")
    telefono = models.PositiveIntegerField(verbose_name="Celular",null=True,blank=True)
    direccion = models.CharField(max_length=100,verbose_name="Direccion",null=True,blank=True)
    empresa = models.ForeignKey(Empresa,on_delete=models.DO_NOTHING,verbose_name="Empresa")
    area = models.ForeignKey(AreaTrabajo,on_delete=models.DO_NOTHING,verbose_name="Area de trabajo")
    cargo = models.ForeignKey(CargoTrabajador,on_delete=models.DO_NOTHING,verbose_name="Cargo del trabajador")
    sctr = models.FileField(upload_to='sctr/',verbose_name="SCTR",blank=True,null=True)
    estado = models.BooleanField(default=True,verbose_name='Activo')
    # codigo_rfid = models.CharField(verbose_name="RFID",max_length=100,null=True,blank=True)
    history = HistoricalRecords()
    def toJSON(self):
        item = model_to_dict(self)
        item["cargo"] = self.cargo.cargo
        item["area"] = self.area.area
        item['sctr'] = self.get_file()

        return item
    class Meta:
        verbose_name = "Trabajador"
        verbose_name_plural = "Trabajadores"
        db_table = "trabajadores"
        ordering = ['id']
    def get_file(self):
        if self.sctr:
            return '{}{}'.format(MEDIA_URL, self.sctr)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')
    def __str__(self) -> str:
        return f"{self.nombre} {self.apellidos}"
class Vehiculos(models.Model):
    trabajador = models.ForeignKey(Trabajadores,on_delete=models.CASCADE,verbose_name="Trabajador",blank=True,null=True)
    marca = models.CharField(max_length=15,verbose_name='Marca del Vehiculo',default='')
    modelo = models.CharField(max_length=20,verbose_name="Modelo vel Vehiculo",default='')
    placa = models.CharField(max_length=6,verbose_name="Placa de rodaje",default='')
    fv_soat = models.DateField(auto_now=True,verbose_name="SOAT-Fecha de Vencimiento")
    # history = HistoricalRecords()

    def toJSON(self):
        item = model_to_dict(self)
        item['trabajador'] = self.trabajador.id
        return item
    class Meta:
        verbose_name = "Vehiculo"
        verbose_name_plural = "Vehiculos"
        db_table = "vehiculos"
        ordering = ['id']
class Parqueo(models.Model):
    numero = models.CharField(max_length=5,verbose_name="Numero de Parqueo",unique=False)
    estado = models.BooleanField(default=True,verbose_name="Estado")
    nombre = models.CharField(max_length=150,verbose_name="Nombre del parqueo",null=True,blank=True)
    empresa = models.ForeignKey(Empresa,on_delete=models.DO_NOTHING,verbose_name="Empresa",null=True,blank=True)
    unidad = models.ForeignKey(Unidad,on_delete=models.DO_NOTHING,verbose_name="unidad",null=True,blank=True)
    puesto = models.ForeignKey(Puesto,on_delete=models.DO_NOTHING,verbose_name="puesto",null=True,blank=True)
    # history = HistoricalRecords()

    class Meta:
        verbose_name = "Parqueo"
        verbose_name_plural = "Parqueos"
        db_table = 'parqueos'
        ordering = ['id']
    def toJSON(self):
        item = model_to_dict(self)
        return item
    def __str__(self) -> str:
        return self.numero
class AsignacionEPPS(models.Model):
    trabajador = models.ForeignKey(Trabajadores,on_delete=models.CASCADE,verbose_name="Trabajador",blank=True,null=True)
    casco = models.BooleanField(default=False,verbose_name="Casco")
    barbiquejo = models.BooleanField(default=False,verbose_name="Barbiquejo")
    botas = models.BooleanField(default=False,verbose_name="Botas punta de acero")
    tapones = models.BooleanField(default=False,verbose_name="Tapones de oido")
    lentes = models.BooleanField(default=False,verbose_name="Lentes de seguridad")
    chaleco = models.BooleanField(default=False,verbose_name="Chaleco reflectivo")
    respirador = models.BooleanField(default=False,verbose_name="Respirador doble via")
    # history = HistoricalRecords()

    def toJSON(self):
        item = model_to_dict(self)
        item['trabajador'] = self.trabajador.id
        return item
    class Meta:
        verbose_name = "Asignacion de EPPS"
        verbose_name_plural = "Asignaciones de EPPS"
        db_table = 'asignacion_epps'
        ordering = ['id']
class AsignacionEV(models.Model):#ASIGNACION DE EQUIPO VEHICULAR
    trabajador = models.ForeignKey(Trabajadores,on_delete=models.CASCADE,verbose_name="Trabajador",blank=True,null=True)
    botiquin = models.BooleanField(default=False,verbose_name="Botiquin")
    extintor = models.BooleanField(default=False,verbose_name="Extintor")
    triangulo_s = models.BooleanField(default=False,verbose_name="Triangulo de Seguridad")
    cono_s = models.BooleanField(default=False,verbose_name="Cono de seguridad")
    taco = models.BooleanField(default=False,verbose_name="taco")
    pertiga = models.BooleanField(default=False,verbose_name="pertiga")
    circulina = models.BooleanField(default=False,verbose_name="Circulina")
    # history = HistoricalRecords()

    def toJSON(self):
        item = model_to_dict(self)
        item['trabajador'] = self.trabajador.id
        return item
    class Meta:
        verbose_name = 'Asignacion de ESV'
        verbose_name = 'Asignaciones de ESV'
        db_table = 'asignacion_ev'
        ordering = ['id']
class IngresoSalida(models.Model):
    trabajador = models.ForeignKey(Trabajadores,on_delete=models.DO_NOTHING,verbose_name="Trabajador")
    usuario = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    fecha_ingreso = models.DateField(auto_created=True,verbose_name='Fecha de ingreso',null=True,blank=True)
    fecha_salida = models.DateField(auto_created=False,verbose_name='Fecha de salida',null=True,blank=True)
    hora_ingreso = models.TimeField(auto_created=True,verbose_name="Hora de ingreso",null=True,blank=True)
    hora_salida = models.TimeField(auto_created=False,verbose_name="Hora de salida",null=True,blank=True)
    placa = models.CharField(max_length=10,verbose_name="Placa del vehiculo",null=True,blank=True)
    n_parqueo = models.ForeignKey(Parqueo, on_delete=models.DO_NOTHING, verbose_name="Numero de parqueo",null=True,blank=True)
    motivo = models.CharField(max_length=200,verbose_name="Motivo del ingreso o salida",null=True,blank=True)
    history = HistoricalRecords()
    class Meta:
        verbose_name = "Ingreso y salida"
        verbose_name_plural = "Ingresos y salidas"
        db_table = "ingresos_salidas"
        ordering = ['id']
    def toJSON(self):
        item = model_to_dict(self)
        item["empresa"] = self.trabajador.empresa.razon_social
        return item
class Salas(models.Model):
    sala = models.CharField(max_length=100,verbose_name="Sala",unique=True)
    estado= models.IntegerField(verbose_name="Estado",default=0,null=True,blank=True)
    empresa = models.ForeignKey(Empresa,on_delete=models.DO_NOTHING,verbose_name="Empresa",null=True,blank=True)
    capacidad = models.PositiveIntegerField(verbose_name="Capacidad",null=True,blank=True)
    unidad = models.ForeignKey(Unidad,on_delete=models.DO_NOTHING,verbose_name="unidad",null=True,blank=True)
    puesto = models.ForeignKey(Puesto,on_delete=models.DO_NOTHING,verbose_name="puesto",null=True,blank=True)
    # history = HistoricalRecords()

    class Meta:
        verbose_name = 'Sala'
        verbose_name_plural = 'Salas'
        db_table = 'salas'
        ordering = ['id']
    def toJSON(self):
        item = model_to_dict(self)
        return item
    def __str__(self) -> str:
        return self.sala
class Visitas(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING,verbose_name="Usuario que Autoriza",null=True,blank=True)
    tipo_documento = models.CharField(max_length=10,choices=[("1","DNI"),("2","C.E"),("3","PASAPORTE")],verbose_name="TIPO DOCUMENTO",blank=True,null=True)
    dni = models.CharField(max_length=10,verbose_name="N° Documento")
    nombre = models.CharField(max_length=50,verbose_name="Nombres")
    apellidos = models.CharField(max_length=50,verbose_name="Apellidos")
    documento_empresa = models.CharField(max_length=15,verbose_name="Nº RUC/DNI/CE/PP",null=True,blank=True)
    empresa = models.CharField(max_length=150,verbose_name="Empresa",null=True,blank=True)

core/erp/views/equipos/views.py
from typing import Any
from django.db import models
from django.http import JsonResponse
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from core.erp.forms import FormEPVisitante
from core.erp.models import EquiposProteccionVisitante
class UpdateViewEquipos(LoginRequiredMixin,UpdateView):
    template_name = 'equipos/create.html'
    model = EquiposProteccionVisitante
    form_class = FormEPVisitante
    success_url = reverse_lazy('erp:visita_list')
    url_redirect = success_url
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)
    def post(self,request,*args,**kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = "No se ingreso ninguna opcion"
        except Exception as e:
            data['error'] = f"Ocurrio un error: {str(e)}"
        return JsonResponse(data)
    def get_object(self, queryset=None):
        return self.model.objects.get(visitante_id=self.kwargs['pk'])
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['title'] = "Equipos de Porteccion"
        context['action'] = 'edit'
        context['list_url'] = self.success_url
        return context

core/erp/views/views.py
from django.shortcuts import render
from django.views.generic import View

class PageNotFoundView(View):
    template_name = '404.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, status=404)

core/erp/templates/visitas/auditoria.html
{% extends 'audi.html' %}
{% load static %}
{% block head_list_ind %}
    <script src="{% static 'salas/js/audi_list.js' %}"></script>
{% endblock head_list_ind %}

core/erp/templates/visitas/create.html
{% extends 'form.html' %}
{% load static %}
{% block head_form %}
    <link href="{% static 'lib/select/css/select2.min.css' %}" rel="stylesheet"/>

    <link href="{% static 'lib/select/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select/js/i18n/es.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

{% endblock head_form %}
{% block form %}
    <div class="row">
        <div class="card col-sm-6">
            <div class="card-header " id="header-title">
                <h6>Datos del visitante</h6>
            </div>
            <div class="card-body">
                
                {{form.user}}
                <label for="id_estado">{{form.estado.label}}</label>
                {{form.estado}}
                <label for="id_tipo_documento">{{form.tipo_documento.label}}</label>
                {{form.tipo_documento}}
                <label for="id_dni">{{form.dni.label}}</label>
                {{form.dni}}
                <div class="row">
                    <div class="col-12 col-md-4 mb-2 mb-md-0">
                        <label for="id_nombre" class="w-100">
                            {{ form.nombre.label }}
                            {{ form.nombre }}
                        </label>
                    </div>
                    <div class="col-12 col-md-6 mb-2 mb-md-0">
                        <label for="id_apellidos" class="w-100">
                            {{ form.apellidos.label }}
                            {{ form.apellidos }}
                        </label>
                    </div>
                    <div class="col-12 col-md-2 d-flex align-items-end">
                        <label >
                            <label></label>
                            <button type="button" class="btn btn-primary" id="search_trabajador" >
                                Buscar
                            </button>
                        </label>
                    </div>
                </div>
                
                <label for="id_p_visita">{{form.p_visita.label}}</label>
                {{form.p_visita}}
                <label for="id_motivo">{{form.motivo.label}}</label>
                {{form.motivo}}
                <div class="row">
                    <div class="col-12 col-md-4 mb-2 mb-md-0">
                        <label for="id_documento_empresa" class="w-100">
                            {{form.documento_empresa.label}}
                            {{form.documento_empresa}}
                        </label>
                    </div>
                    <div class="col-12 col-md-6 mb-2 mb-md-0">
                        <label for="id_empresa" class="w-100">
                            {{form.empresa.label}}
                            {{form.empresa}}
                        </label>
                    </div>
                    <div class="col-12 col-md-2 d-flex align-items-end">
                        <label >
                           <label for="id_search_documento_empresa"></label>
                            <button type="button" class="btn btn-success" id="search_documento_empresa">
                                Buscar
                            </button>
                        </label>
                    </div>
                </div>
                <label for="id_cargo">{{form.cargo.label}}</label>
                {{form.cargo}}
                <label for="id_sctr_salud">{{form.sctr_salud.label}}</label>
                {{form.sctr_salud}}
                
            </div>
            <div class="card-footer">
                
            </div>
        </div>
        <div class="card col-sm-6">
            <div class="card-header " id="header-title">
                <h6>Mas Datos</h6>
            </div>
            <div class="card-body">
                <label for="id_fecha">{{form.fecha.label}}</label>
                {{form.fecha}}
                <label for="id_h_inicio">{{form.h_inicio.label}}</label>
                {{form.h_inicio}}
                {{form.h_llegada}}
                <label for="id_h_termino">{{form.h_termino.label}}</label>
                {{form.h_termino}}
                <label for="id_sala">{{form.sala.label}}</label>
                {{form.sala}}
                <!-- <label for="id_tipo">{{form.tipo.label}}</label> -->
                {{form.tipo}}
                <label for="id_v_marca">{{form.v_marca.label}}</label>
                {{form.v_marca}}
                <label for="id_v_modelo">{{form.v_modelo.label}}</label>
                {{form.v_modelo}}
                <label for="id_v_placa">{{form.v_placa.label}}</label>
                {{form.v_placa}}
                <label for="id_fv_soat">{{form.fv_soat.label}}</label>
                {{form.fv_soat}}
                <label for="id_strc_salud">{{form.strc_salud.label}}</label>
                {{form.strc_salud}}
                <label for="id_n_parqueo">{{form.n_parqueo.label}}</label>
                {{form.n_parqueo}}
              
            </div>
            <div class="card-footer">
    
            </div>
        </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Lista de trabajadores</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      
            </div>
          </div>
        </div>
      </div>
{% endblock %}
{% block javascript %}
    <script>
        $('#id_user').val('{{request.user.id}}')
        $(function(){
            $('.select2').select2({
                theme:'bootstrap4',
                languaje:'es'
            });
        });
        flatpickr("#id_fecha", {
            minDate:"today",
            enableTime: false,
            defaultDate: $("#id_fecha").val() || "today",
            dateFormat: "Y-m-d", 
            locale: {
                firstDayOfWeek: 1, 
                weekdays: {
                    shorthand: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
                    longhand: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                },
                months: {
                    shorthand: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                    longhand: [
                        'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                    ],
                },
            }
        });
        
        </script>
        <script src="{% static 'visitas/js/form.js' %}"></script>
{% endblock javascript %}

core/erp/templates/visitas/list.html
{% extends 'list.html' %}
{% load static %}
{% block head_list %}

    <script src="{% static 'visitas/js/list.js' %}"></script>
{% endblock %}

{% block columnas %}
    <tr id="header-title">
        <th scope="col">#ID</th>
        <th scope="col">ESTADO</th>
        <th scope="col">NOMBRES Y APELLIDOS</th>
        <th scope="col" >FECHA INGRESO</th>
        <!-- <th scope="col">H.INICIO PROGRAMADO.</th> -->
        <th scope="col">HORA INGRESO</th>
        <th scope="col">FECHA SALIDA</th>
        <!-- <th scope="col">H.FINAL PROGRAMADO.</th> -->
        <th scope="col">HORA SALIDA</th>
        <th scope="col">DNI</th>
        <th scope="col">ACOMPAÑ.</th>
        <th scope="col">CARGO</th>
        <th scope="col">EMPRESA</th>
        <th scope="col">MOTIVO</th>
        <th scope="col">SALA</th>
        <th scope="col">SCTR</th>
        <th scope="col">PERSONA A QUIEN VISITA</th>
        <th scope="col">DOCUMENTOS</th>
        <th scope="col">VEHICULO</th>
        <th scope="col">EQUIPOS</th>
        <th scope="col">OPCIONES</th>
    </tr>

{% endblock %}

{% block filas %}

{% endblock %}

{% block javascript %}
   
   <script>
    var user_supervised = JSON.parse('{{ user_supervised|safe}}')
   </script>    

{% endblock %}